"""Revenue opportunity analysis, regenerated from Cube (GoalEarn Project 03 deliverable).

Writes docs/revenue_opportunity.md. Every number in it comes from Cube's governed metrics
on the latest run date, so the document can be re-run and checked, never hand-edited.

Usage, from the project folder with Cube running:
    python scripts/revenue_opportunity.py
"""
import datetime as dt
import json
import os
import sys
import time
import urllib.parse
import urllib.request
from collections import defaultdict
from pathlib import Path

API = os.environ.get("CUBE_API_URL", "http://localhost:4000/cubejs-api/v1").rstrip("/")
OUT = Path("docs/revenue_opportunity.md")
BOXES = [  # box, who acts, motion
    ("pqa", "Sales", "Call this week from the Monday brief: an upgrade conversation on free, expansion on paid plans."),
    ("heavy_user", "Product", "In-app upgrade nudges (Amplitude cohort). High usage, little buying intent: no call yet."),
    ("tyre_kicker", "Product / onboarding", "Onboarding help (Amplitude cohort). Buying intent without usage: help them reach value."),
    ("not_now", "Nobody", "No action. Re-scored every week."),
]
PLANS = ["free", "scale", "performance"]


def load(query):
    url = f"{API}/load?query=" + urllib.parse.quote(json.dumps(query))
    for _ in range(30):
        with urllib.request.urlopen(url, timeout=60) as resp:
            body = json.loads(resp.read().decode("utf-8"))
        if body.get("error") == "Continue wait":
            time.sleep(2)
            continue
        if "error" in body:
            raise SystemExit(f"STOP: Cube error: {body['error']}")
        return body["data"]
    raise SystemExit("STOP: Cube kept answering Continue wait")


def table(header, rows):
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def main():
    latest = load({"measures": ["org_scores.eligible_orgs"],
                   "timeDimensions": [{"dimension": "org_scores.run_date", "granularity": "day"}],
                   "order": {"org_scores.run_date": "desc"}, "limit": 1})[0]["org_scores.run_date.day"][:10]
    on_day = {"member": "org_scores.run_date", "operator": "inDateRange", "values": [latest, latest]}
    orgs = load({"dimensions": ["org_scores.organization_id", "org_scores.quadrant", "org_scores.plan_type",
                                "org_scores.n_users", "org_scores.pipelines_run"],
                 "filters": [on_day], "limit": 5000})
    cube_count = int(float(load({"measures": ["org_scores.eligible_orgs"], "filters": [on_day]})[0]
                           ["org_scores.eligible_orgs"]))
    if len(orgs) != cube_count:
        raise SystemExit(f"STOP: {len(orgs)} org rows but Cube counts {cube_count} eligible orgs")

    agg = defaultdict(lambda: {"orgs": 0, "users": 0, "pipelines": 0})
    for o in orgs:
        for key in ((o["org_scores.quadrant"], None), (o["org_scores.quadrant"], o["org_scores.plan_type"])):
            a = agg[key]
            a["orgs"] += 1
            a["users"] += int(float(o["org_scores.n_users"] or 0))
            a["pipelines"] += int(float(o["org_scores.pipelines_run"] or 0))
    total_orgs = len(orgs)
    total_users = sum(agg[(b, None)]["users"] for b, _, _ in BOXES)

    out_row = load({"measures": ["outcomes.pqa_orgs", "outcomes.called_pqas", "outcomes.meetings_booked"],
                    "filters": [{"member": "outcomes.run_date", "operator": "inDateRange", "values": [latest, latest]}]})
    out_row = out_row[0] if out_row else {}
    called = int(float(out_row.get("outcomes.called_pqas") or 0))
    meetings = int(float(out_row.get("outcomes.meetings_booked") or 0))

    pqa = agg[("pqa", None)]
    pqa_free = agg[("pqa", "free")]
    heavy_free = agg[("heavy_user", "free")]
    motions = [(b, who, agg[(b, None)]["orgs"], agg[(b, None)]["users"], agg[(b, None)]["pipelines"], what)
               for b, who, what in BOXES]
    by_plan = [(b,) + tuple(f"{agg[(b, p)]['orgs']} ({agg[(b, p)]['users']})" for p in PLANS) for b, _, _ in BOXES]

    doc = f"""# Revenue opportunity analysis

Generated by `scripts/revenue_opportunity.py` from Cube's governed metrics on {dt.date.today().isoformat()},
for the list of **{latest}**. Score v0, unvalidated: expert weights, not yet checked against real outcomes.
Do not edit by hand; re-run the script.

## The question

Where is the revenue opportunity in this week's list, and which team should act on each part of it?

There is no price, revenue or plan-history data, so the opportunity is sized in **accounts and users**,
not money. The last section shows what it takes to turn this into money.

## The four boxes and who acts

{total_orgs} eligible organizations with {total_users} users. Pipelines are runs in the 90 days before the run date.

{table(["Box", "Who acts", "Orgs", "Users", "Pipelines", "Motion"], motions)}

## Boxes by plan

Organizations (users) per box and plan.

{table(["Box", "free", "scale", "performance"], by_plan)}

## What this says

- **Sales has {pqa['orgs']} accounts and {pqa['users']} users to work this week.** {pqa_free['orgs']} of them
  ({pqa_free['users']} users) are on the free plan: that is the upgrade conversation. The other
  {pqa['orgs'] - pqa_free['orgs']} already pay, so the conversation is about expansion.
- **The biggest self-serve pool is free-plan heavy users: {heavy_free['orgs']} organizations,
  {heavy_free['users']} users.** They use the product a lot but show no buying intent, so a call would be
  early; an in-app upgrade nudge fits better.
- **Tyre kickers ({agg[('tyre_kicker', None)]['orgs']} organizations)** look at buying without using the
  product much. Onboarding help comes before any sales conversation.
- **What happened so far on this list:** {called} of {pqa['orgs']} PQAs have a logged call outcome,
  {meetings} meetings booked. The outcomes loop (Monday brief buttons, `log_outcome`) fills this in.

## Turning accounts into money later

Expected new revenue from one week's PQAs =
sum over PQA accounts of P(meeting) x P(win | meeting) x users x (target plan price - current plan price).

| Input | Where it comes from | Status |
|---|---|---|
| P(meeting) | `review_outcomes` meeting rate for PQAs | Waiting for at least 30 called accounts |
| P(win given meeting) | Opportunity outcomes from Salesforce | Not in this data |
| Price per user per plan | GoalEarn | Not in this data |
| Plan history | GoalEarn (did accounts like these upgrade before?) | Not in this data |

## Limits

- The score is v0 and unvalidated: no outcome has confirmed the weights yet.
- Users are people in the product, not paid seats; the seat model is unknown.
- The plan is a snapshot from the organizations table, not a history.
- The data is synthetic (a CircleCI-shaped simulation from GoalEarn).
"""
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(doc, encoding="utf-8")
    print(f"wrote {OUT}: {total_orgs} orgs, {total_users} users on {latest}; "
          f"PQAs {pqa['orgs']} ({pqa['users']} users), free-plan PQAs {pqa_free['orgs']}, "
          f"free heavy users {heavy_free['orgs']}; outcomes {called} called, {meetings} meetings")


if __name__ == "__main__":
    sys.exit(main())
